## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc1..aaaaaaaakuxrucuh4ucsx6chmvjwkvyqcd7af7kcxiaguaa6lr7z57vegs4q"
  is_repository_created_on_first_push = "true"
}

