## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_igw {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-05-26T10:26:15.660Z"
  }
  display_name = "igw-test"
  enabled      = "true"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_terraform_practice.id
}

resource oci_core_subnet export_public-subnet {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "192.168.0.0/27"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-05-26T10:26:04.941Z"
  }
  ##dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-terraform_practice.id
  display_name    = "public-subnet-test"
  dns_label       = "publicsubnet"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_terraform_practice.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_terraform_practice.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_terraform_practice.id
}

resource oci_core_vcn export_terraform_practice {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "192.168.0.0/24",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-05-26T10:23:30.750Z"
  }
  display_name = "terraform_practice-test"
  dns_label    = "terraformtest"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_security_list export_Default-Security-List-for-terraform_practice {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-05-26T10:23:30.750Z"
  }
  display_name = "Default Security List for terraform_practice"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "192.168.0.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_terraform_practice.default_security_list_id
}

resource oci_core_default_route_table export_Default-Route-Table-for-terraform_practice {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-05-26T10:23:30.750Z"
  }
  display_name = "Default Route Table for terraform_practice"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_terraform_practice.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_igw.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_private_ip export_OCI-Instance-Terraform {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-06-03T12:43:04.079Z"
  }
  display_name = "OCI-Instance-Terraform-test"
  freeform_tags = {
  }
  hostname_label = "oci-instance-terraform-test"
  ip_address     = "192.168.0.6"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljt5y7n7bayp6r4cb2tc3qfc5ly2lwcuukragyq7eblbhegj3r7tyba"
}

resource oci_core_instance export_OCI-Instance-Terraform_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "OS Management Hub Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute RDMA GPU Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute HPC RDMA Auto-Configuration"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute HPC RDMA Authentication"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Cloud Guard Workload Protection"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    is_live_migration_preferred = "true"
    recovery_action             = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--qCah-US-ASHBURN-AD-1
  #capacity_reservation_id = <<Optional value not found in discovery>>
  #cluster_placement_group_id = <<Optional value not found in discovery>>
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  #compute_cluster_id = <<Optional value not found in discovery>>
  create_vnic_details {
    #assign_ipv6ip = <<Optional value not found in discovery>>
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
      "Oracle-Tags.CreatedOn" = "2024-06-03T12:43:04.079Z"
    }
    display_name = "OCI-Instance-Terraform"
    freeform_tags = {
    }
    hostname_label = "oci-instance-terraform"
    #ipv6address_ipv6subnet_cidr_pair_details = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "192.168.0.6"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_public-subnet.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/samsin16@in.ibm.com"
    "Oracle-Tags.CreatedOn" = "2024-06-03T12:43:03.906Z"
  }
  display_name = "OCI-Instance-Terraform-test"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-1
  freeform_tags = {
  }
  #instance_configuration_id = <<Optional value not found in discovery>>
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "true"
    network_type                        = "PARAVIRTUALIZED"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  #launch_volume_attachments = <<Optional value not found in discovery>>
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCapWYv/NeJ9aI7CltVwOlDKkhos/X+UxAXzIsFsqmFREX2lP8Lxfm/XEWtD8ZZ1GyBwmE1yzYRpAqY4HmkamWP+tbPcSyOmVI3PJjZwuDCOGSQbt2okYWPaMBnPSs36W+1vf08ZSxfI+JrQ0bpNUA7hemRGvKEDkxu1BfJU/YJJ9EmDKlvP0SdtbA8oK80Ks2Rn+heNf7X8gNgsBPV1qrHbXVDKKThhJIsRTQjlJ4Iwz9EyBpMmbSXxzjrhPKK2k/97cX+5xJuaf8R7KACift5PVDf9djbF8RpghrgL251xmRX5I5NH+jka02zmZM+RKTCbFyFSAaxnlnhioDmwtNd aws"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  #preserve_data_volumes_created_at_launch = <<Optional value not found in discovery>>
  shape = "VM.Standard.E2.1.Micro"
  shape_config {
    baseline_ocpu_utilization = ""
    memory_in_gbs             = "1"
    #nvmes                     = "0"
    ocpus                     = "1"
    vcpus                     = "2"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    boot_volume_vpus_per_gb = "10"
    #instance_source_image_filter_details = <<Optional value not found in discovery>>
    #is_preserve_boot_volume_enabled = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_OCI-Instance-Terraform_1
    source_type = "image"
  }
  ##state = "RUNNING"
  #update_operation_constraint = <<Optional value not found in discovery>>
}
