## This configuration was generated by terraform-provider-oci

data oci_objectstorage_namespace export_namespace {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
}
